---
- name: gather nova pubkeys
  shell: cat /var/lib/nova/.ssh/id_rsa.pub
  register: nova_pubkey

- name: gather hostkeys
  shell: cat /etc/ssh/ssh_host_rsa_key.pub
  register: ssh_hostkey

- name: nova authorized_keys
  template: src=var/lib/nova/ssh/authorized_keys dest=/var/lib/nova/.ssh/authorized_keys owner=nova group=nova mode=0600

- name: nova known_hosts
  template: src=var/lib/nova/ssh/known_hosts dest=/var/lib/nova/.ssh/known_hosts owner=nova group=nova mode=0600

- template: src=var/lib/nova/ssh/verify-ssh dest=/var/lib/nova/.ssh/verify-ssh owner=nova group=nova mode=0755

- name: verify ssh among compute nodes
  shell: /var/lib/nova/.ssh/verify-ssh

